---
version: "3"

services:
  jweaston-redis:
    image: jweaston/final-project-db:latest
    container_name: jweaston-redis
    ports: 
      - 6389:6379
    user: "827385:815499"
    volumes:
      - ../data/:/data/

  jweaston-api:
    image: jweaston/final-project-api:latest
    container_name: jweaston-api
    environment: 
      - REDIS_IP = jweaston-redis
    ports:
      - 5009:5000

  jweaston-worker:
    image: jweaston/final-project-wrk:latest
    container_name: jweaston-worker
    environment: 
      - REDIS_IP = jweaston-redis

...