---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jweaston-final-flask-deployment
  labels:
    app: jweaston-flask
    username: jweaston
    env: prod
spec:
  replicas: 
  selector:
    matchLabels:
      app: jweaston-flask
      username: jweaston
      env: prod
  template:
    metadata:
      labels:
        app: jweaston-flask
        username: jweaston
        env: prod
    spec:
      containers:
        - name: jweaston-flask
          imagePullPolicy: Always
          image: jweaston/final-project:latest
          env:
          - name: FLASK_APP
            value: "api.py"
          - name: REDIS_IP
            value: "10.98.243.144"
          ports:
          - name: http
            containerPort: 5000