---
apiVersion: v1
kind: Service
metadata:
  name: jweaston-final-flask-service
  labels:
    username: jweaston
    env: prod
spec:
  type: ClusterIP
  selector:
    app: jweaston-flask
    username: jweaston
    env: prod
  ports:
  - name: jweaston-flask
    port: 5000
    targetPort: 5000