---
apiVersion: v1
kind: Service
metadata:
  name: jweaston-final-redis-service
  labels:
    username: jweaston
    env: prod
spec:
  type: ClusterIP
  selector:
    app: jweaston-final-redis
    username: jweaston
    env: prod
  ports:
  - name: redis-database
    port: 6379
    targetPort: 6379