---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jweaston-final-redis-deployment
  labels:
    app: jweaston-final-redis
    username: jweaston 
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jweaston-final-redis
      username: jweaston
      env: prod
  template: 
    metadata:
      labels:
        app: jweaston-final-redis
        username: jweaston
        env: prod
    spec:
      containers:
        - name: redis
          image: redis:5.0.0
          volumeMounts:
          - name: jweaston-final-redis-data
            mountPath: "/data"
      volumes:
      - name: jweaston-final-redis-data
        persistentVolumeClaim:
          claimName: jweaston-final-redis-data