---
apiVersion: v1
kind: Service
metadata:
  name: jweaston-test-flask-service
  labels:
    username: jweaston
    env: test
spec:
  type: ClusterIP
  selector:
    app: jweaston-flask
    username: jweaston
    env: test
  ports:
  - name: jweaston-flask
    port: 5000
    targetPort: 5000