---
apiVersion: v1
kind: Service
metadata:
  name: jweaston-test-redis-service
  labels:
    username: jweaston
    env: test
spec:
  type: ClusterIP
  selector:
    app: jweaston-test-redis
    username: jweaston
    env: test
  ports:
  - name: redis-database
    port: 6379
    targetPort: 6379