---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jweaston-hw7-redis-data
  labels:
    username: jweaston
    env: hw7
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi